### ISSUE TITLE
After reboot of HA custom component/integration will not start

### ISSUE THREAD

**Issue by DanielWeeber** [koush/ha_scrypted#10]
Hey,

custom component will not start/connect to scrypted after a reboot of HA (im using HassIO in this case) because of a racing condition. The custom component tries to reach scrypted earlier as its able to start.

If I go to integrations -> scypted and click on "reload" after HA has booted fully everything is working fine

<img width="501" alt="image" src="https://github.com/koush/ha_scrypted/assets/2935130/9742e916-5b31-4482-87dc-fac0b7aedc25">

**Comment by koush** [comment]
https://github.com/koush/ha_scrypted/commit/834e9212bfeb6f4d32e79fe7be90f250e6573726
