### ISSUE TITLE
Addon should not enforce SSL

### ISSUE THREAD

**Issue by mister2d** [koush/ha_scrypted#11]
Please allow the add-on to use HTTP or HTTPS endpoints.

Use case:

- When containers are run in a sidecar based service mesh, SSL/TLS is taken leveraged at that level.  
- Home Assistant runs on the Alpine base container image. If one did use an external HTTPS endpoint using the FQDN, you will run into the [ndots issue](https://github.com/gliderlabs/docker-alpine/issues/255).

**Comment by 0dragosh** [comment]
@koush I run scrypted NVR with 8 cams in Kubernetes and this affects me, I cannot connect my Home Assistant to scrypted. Any way you could add support for just a url and not do the port parsing and enforcing https?

**Comment by koush** [comment]
> @koush I run scrypted NVR with 8 cams in Kubernetes and this affects me, I cannot connect my Home Assistant to scrypted. Any way you could add support for just a url and not do the port parsing and enforcing https?

This sounds like a configuration issue. Make sure the correct ports are forwarded/exposed. 10443.

**Comment by mister2d** [comment]
> > @koush I run scrypted NVR with 8 cams in Kubernetes and this affects me, I cannot connect my Home Assistant to scrypted. Any way you could add support for just a url and not do the port parsing and enforcing https?
> 
> This sounds like a configuration issue. Make sure the correct ports are forwarded/exposed. 10443.

Not exactly. As mentioned in the issue, the default configuration is used. In my environment there also isn't a need to forward or expose ports.

What's happening is that the code is enforcing https when the scheme should be configurable (http:// or https://):  

https://github.com/koush/ha_scrypted/blob/b805e00c7f70bdd0b55722e75db1a7b5a0f7cc5f/custom_components/scrypted/http.py#L43  

https://github.com/koush/ha_scrypted/blob/b805e00c7f70bdd0b55722e75db1a7b5a0f7cc5f/custom_components/scrypted/http.py#L83  

Also, implicitly trusting any certificate no matter the signer presents a security issue and isn't best practice:  

https://github.com/koush/ha_scrypted/blob/b805e00c7f70bdd0b55722e75db1a7b5a0f7cc5f/custom_components/scrypted/http.py#L47  

https://github.com/koush/ha_scrypted/blob/b805e00c7f70bdd0b55722e75db1a7b5a0f7cc5f/custom_components/scrypted/http.py#L189

**Comment by 0dragosh** [comment]
> > @koush I run scrypted NVR with 8 cams in Kubernetes and this affects me, I cannot connect my Home Assistant to scrypted. Any way you could add support for just a url and not do the port parsing and enforcing https?
> 
> This sounds like a configuration issue. Make sure the correct ports are forwarded/exposed. 10443.

@koush t’s not a configuration issue. I run Scrypted inside the cluster on 11080 and on HTTP. I want to be able to input a url with scheme and port for the HASS integration.

**Comment by gorfreed** [comment]
Enforced SSL makes no sense especially when Scrypted runs on a local network and remote access only taking place via Scrypted Cloud. It also makes it impossible to proxy pass for embedding into advanced contexts with other services (e.g. dashboards). I wonder what makes this a requirement.

**Comment by koush** [comment]
webrtc does not work with ssl disabled, same with microphone access, etc. this is a nonstarter.

**Comment by gorfreed** [comment]
Well, I still don't get it. Other scripts do not need this and it comes up as possible source of error everywhere, even if it might not be directly involved. For instance, I am now trying a new Home Assistant setup running on VMWare Windows, while running Scrypted Desktop on the same machine in parallel. For some reason I am failing to connect HA with the Scrypted Desktop instance, always receiving an "Unknown error occurred" message.

![image](https://github.com/koush/ha_scrypted/assets/6634117/abdcfeee-d1df-4172-bd21-1c372a6e2b92)

Upon looking into the HA system logs for possible causes, guess what I find:

![image](https://github.com/koush/ha_scrypted/assets/6634117/b341b9d4-d390-4d91-9745-945f1d984f1a)

I have no clue whether this is actually whats causing the error, but I feel any error with Scrypted has a high likelyhood to be SSL related, especially considering anything else on HA runs without certificates.

**Comment by koush** [comment]
please refrain from opening new issues on this. supporting insecure contexts will just result in a different class of bugs being opened instead regarding the aforementioned limitations of insecure http contexts.

**Comment by stromdriver** [comment]
having same issue , have tried multiple host configurations, *hassgreen ip* with and without :10443 same for 127.0.0.1 including trying them in scrypted settings server address
 just constant 'uknown error occured'  new to HA
