### ISSUE TITLE
Unknown error occurred when trying to connect to Scrypted

### ISSUE THREAD

**Issue by gorfreed** [koush/ha_scrypted#13]
(Continued from closed [Addon should not enforce SSL](https://github.com/koush/ha_scrypted/issues/11)

Other scripts do not need to enforce SSL and it comes up as possible source of error everywhere, even if it might not be directly involved. For instance, I am now trying a new Home Assistant setup running on VMWare Windows, while running Scrypted Desktop on the same machine in parallel. Both HA in VMWare and Scrypted Desktop work flawlessly on their own, but for some reason I am failing to connect HA with the Scrypted Desktop instance, always receiving an "Unknown error occurred" message.

![image](https://github.com/koush/ha_scrypted/assets/6634117/abdcfeee-d1df-4172-bd21-1c372a6e2b92)

Upon looking into the HA system logs for possible causes, guess what I find:

![image](https://github.com/koush/ha_scrypted/assets/6634117/b341b9d4-d390-4d91-9745-945f1d984f1a)

I have no clue whether this is actually whats causing the error, but I feel any error with Scrypted has a high likelyhood to be SSL related, especially considering anything else on HA runs without certificates.

Note: Port 11080 has been cleared in the Windows Firewall

**Comment by koush** [comment]
you're trying to use the insecure port.

**Comment by gorfreed** [comment]
No I am not. I am using YOUR default settings without any customization, set up as per your documentation. As others have pointed out elsewhere, your software decided to use 11080 instead of the one in your documentation. 

I suggest you stop closing unresolved issues.

**Comment by koush** [comment]
11080 is the insecure port. the directions in your screenshot say `you must use an HTTPS endpoint`.

**Comment by gorfreed** [comment]
But thats what I am saying, there is NO OPTION to select or customize the port on Scrypted Desktop! Where would I make this choice? Why is the correct one not selected by default?!

**Comment by koush** [comment]
> But thats what I am saying, there is NO OPTION to select or customize the port on Scrypted Desktop! Where would I make this choice? Why is the correct one not selected by default?!

scrypted desktop will use 10443 for the https port. that's the port you want to enter in the screenshot above.

**Comment by Maotechh** [comment]
@koush Hey bro, the same error seems to occur to me, but it seems to have the different cause.(since I used the 10443 port)
<img width="1512" alt="截屏2024-11-12 12 18 17" src="https://github.com/user-attachments/assets/f94ec3d9-4df4-45f7-8030-eb5a915ba3ae">
I installed it via HACS.
I have 215.04MB of disk space left.(I don't know whether it is the cause)
