### ISSUE TITLE
Custom Component not accepting Host address

### ISSUE THREAD

**Issue by dcarpio01** [koush/ha_scrypted#15]
The custom component was working before the 24.4 update. Now the entities don't load and I can't delete and readd it on the integrations page.

![Screenshot 2024-04-06 at 8 40 44 PM](https://github.com/koush/ha_scrypted/assets/13407626/4ffdc8f9-89b9-472f-9153-bd89d38e19cd)

![Screenshot 2024-04-07 at 11 10 30 AM](https://github.com/koush/ha_scrypted/assets/13407626/7f38e9fb-7769-4451-a13c-a17ca3c9f77f)

**Comment by koush** [comment]
maybe restart ha, working fine here.

**Comment by dcarpio01** [comment]
Same issue on reboot. Scrypted works on HAOS, but the custom component just will not accept anything in the Host box.

**Comment by koush** [comment]
I see, I just changed it to not validate the url. should be fixed now if you update.
