### ISSUE TITLE
Setup of Customk HA component failing

### ISSUE THREAD

**Issue by superpsych0** [koush/ha_scrypted#19]
Hello,

Trying to get a setup of Scrypted hosted on Docker in UnRAID (seen below, working!)

![image](https://github.com/user-attachments/assets/e8344fe6-d344-4c44-ad24-281930686604)

to talk to an HA installation, installed the custom component via HACS and trying the below values (100% sure I'm getting the user/password right, filling them in from a password manager!)

![image](https://github.com/user-attachments/assets/8a3b6543-b1ea-4e37-9a6c-602e5068e00b)

but getting this "Unknown Error"

![image](https://github.com/user-attachments/assets/637c2281-ddf3-48fa-99a8-149c53e9655e)

Is this because of the server not using an HTTPS endpoint?

**Comment by koush** [comment]
wrong port.
