### ISSUE TITLE
Chrome/Chromium tab on macOS/Windows is crashing when viewing HA dashboard with NVR cards

### ISSUE THREAD

**Issue by kersten-lohmeyer** [koush/ha_scrypted#24]
- [X] I have searched the issue tracker for an existing issue.

**Describe the bug**
Chrome/Chromium (newest version available) tab on macOS/Windows is crashing when viewing HA dashboard with NVR cards. I disabled all extensions to make sure that's not the problem. I cleared all cache and even reinstalled Chrome and also deleted all files in Application Support. Chromium was a new install anyway.

Works fine with Firefox though.

**To Reproduce**
Open your HA dashboard with NVR cards on it in Google Chrome or Chromium. When the NVR cards are removed Chrome and Chromium tabs don't crash anymore.

**Expected behavior**
Display of images of motion events and my cam still picture. Instead the cards don't display anything and the browser tab freezes.

**Screenshots**
<img width="313" alt="grafik" src="https://github.com/user-attachments/assets/915ac846-1045-4b0e-bb6e-177a28803ba1">

**Desktop (please complete the following information):**
 - OS: macOS or Windows
 - Browser: Chrome or Chromium
 - Version: most current version

**Additional context**
The NVR runs in the official Proxmox container and auto updates are enabled.

**Comment by koush** [comment]
was this resolved? I havent looked yet

**Comment by kersten-lohmeyer** [comment]
It’s resolved. Problem was the new local network permission setting in Sequoia.
