### ISSUE TITLE
Snapshots in HA OK, but no video

### ISSUE THREAD

**Issue by jchrismills** [koush/ha_scrypted#28]
- [ ] I have searched the issue tracker for an existing issue.

**Describe the bug**
Everything seems to work until you wan to play a clip or watch live. The thumbnails and snapshots all appear correctly and for a millisecond, when you click on a video or live shot, the first initial frame will flash and then is gone.

**To Reproduce**
Play video from the scrypted HACS add-in dashboard

**Expected behavior**
A video, moving pictures, to display on my screen.

**Screenshots**
A screenshot would be of a black screen so not very useful. 

**Desktop (please complete the following information):**
 - OS: macOS 15.1
 - Browser Safari 18.1

**Smartphone (please complete the following information):**
 - Device: iPhone 16 Pro
 - OS: 18.2
 - Browser safari
 - Version 18.2

Interestingly, it works perfectly fine in the HomeAssistant iOS App and the HomeAssistant webgui (in Safari and Chrome), the only place there does seem to be an issue is the actual HomeAssistant macOS native App.

**Comment by koush** [comment]
ha macOS native app does not support webrtc and they need to implement/enable that.

**Comment by koush** [comment]
actually seems to be a macOS webview limitation and HA uses macOS webview. the nvr desktop app uses electron, no such limitation there. can't fix this in any case as its 2 repos downstream.
